
version: '3'

services: 
  app:
    build: 
      context: node
    networks: 
      - node-network
    volumes: 
      - ./node:/usr/src/app
    container_name: app
    tty: true
    ports: 
      - "3000:3000"
    entrypoint: dockerize -wait tcp://db:3306 -timeout 20s docker-entrypoint.sh


  db:
    image: mysql:5.7
    container_name: mysql
    restart: always
    tty: true
    volumes: 
      - ./mysql:/var/lib/mysql
    environment: 
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks: 
      - node-network

networks: 
  node-network:
    driver: bridge   